Added Sign-in and Sign-up forms
greenpress/blog-front pull request #29
Opened 2020-09-24 18:39 UTC by dani98000

This is my first time using Vue, so apologies in advance for the shitty code, I'd love to hear I can improve this!
TODO:
* Actually call the api to sign in and sign up
* Add auth section to the header (Authenticated? Show login and signup links : Display the user name and signout link)
![Screenshot from 2020-09-24 21-38-16](https://user-images.githubusercontent.com/12670492/94185726-5611e780-feae-11ea-8618-358d558857d9.png)

2020-09-25 07:26 UTC, davidmeirlevy requested changes

2020-09-25 07:26 UTC, davidmeirlevy commented on themes/damal/Layout.vue
> +    <div class="content">
instead of adding a new `div`, you can maker the footer with `position: sticky`.
it would be shorter.

2020-09-25 07:26 UTC, davidmeirlevy commented on pages/signin/index.vue
> +<template>
if this path is static, you can create a `signin.vue` file at the `/pages` folder, and you don't need a `signin` folder with an `index.vue` file.

2020-09-25 07:26 UTC, davidmeirlevy commented on pages/signin/index.vue
> +import SigninForm from "../../.current_theme/components/SigninForm";
as the developers of the front-blog infrastructure, we only import components that on the root level of the theme, so it should import the `SignIn.vue` component from the top level of the theme folder.
the secondary level is whatever the theme-developer will want to have.

2020-09-25 07:26 UTC, davidmeirlevy commented on pages/signup/index.vue
> +<template>
if this path is static, you can create a `signup.vue` file at the `/pages` folder, and you don't need a `signin` folder with an `index.vue` file.

2020-09-25 07:26 UTC, davidmeirlevy commented on pages/signup/index.vue
> +import SignupForm from "../../.current_theme/components/SignupForm";
as the developers of the front-blog infrastructure, we only import components that on the root level of the theme, so it should import the `SignUp.vue` component from the top level of the theme folder.
the secondary level is whatever the theme-developer will want to have.

2020-09-25 07:26 UTC, davidmeirlevy commented on themes/damal/components/Form.vue
> +        button_title: String,
consider using camelCase

2020-09-25 07:26 UTC, davidmeirlevy commented on themes/damal/components/Form.vue
> +        next_page: String,
consider using camelCase

2020-09-25 07:26 UTC, davidmeirlevy commented on themes/damal/components/Form.vue
> +        onSubmit: Function,
at Vue, we don't pass the functions as props, but instead we `emit()` the events.

2020-09-25 07:26 UTC, davidmeirlevy commented on themes/damal/components/Form.vue
> +<style>
add scoped css

2020-09-25 07:26 UTC, davidmeirlevy commented on themes/damal/components/FormInput.vue
> +        console.log("validaoters:", props.validators);
remove console.log

2020-09-25 07:26 UTC, davidmeirlevy commented on themes/damal/components/FormInput.vue
> +.inputBox {
consider using kebab-case for CSS classes

2020-09-25 07:26 UTC, davidmeirlevy commented on themes/damal/components/SigninForm.vue
> +                email: [isEmail()],
I believe you meant to pass the function, and not to execute it.

2020-09-25 07:26 UTC, davidmeirlevy commented on themes/damal/components/SigninForm.vue
> +            message: "Don't have an account yet? Sign Up",
if the text is static, just put it in the template

2020-09-25 07:26 UTC, davidmeirlevy commented on themes/damal/components/SignupForm.vue
> +            confirm_password: "",
consider camelCase

2020-09-25 07:59 UTC, dani98000 commented on themes/damal/components/SigninForm.vue
> +                email: [isEmail()],
I did meant to execute it :)
```js
const isEmail = () => {
  const re = /\S+@\S+\.\S+/;
  return (input) => (re.test(input) ? null : "Must be a valid email address");
};
```

2020-09-25 09:44 UTC, davidmeirlevy requested changes

2020-09-25 09:44 UTC, davidmeirlevy commented on themes/damal/Layout.vue
> +@media all and (min-width: 500px) {
You removed the “app” class..
Make sure this behavior should remain.

2020-09-25 09:44 UTC, davidmeirlevy commented on pages/signin.vue
> +import SigninForm from "../.current_theme/components/SigninForm";
The import should load a root theme component with the same name, but with capitalized name. (E.g: SignIn.vue)

2020-09-25 09:44 UTC, davidmeirlevy commented on pages/signup.vue
> +import SignupForm from "../.current_theme/components/SignupForm";
The import should load a root theme component with the same name, but with capitalized name. (E.g: SignUp.vue)

2020-09-25 09:44 UTC, davidmeirlevy commented on themes/damal/Layout.vue
> -	<div class="app">
You removed the “app” class, make sure the UX wasn’t damaged.

2020-09-25 09:44 UTC, davidmeirlevy commented on themes/damal/components/Form.vue
> +<style>
Use scoped css

2020-09-25 09:44 UTC, davidmeirlevy commented on themes/damal/components/Form.vue
> +<style scoped>
Does this file has 2 styles? A bit weird..

2020-09-25 09:44 UTC, davidmeirlevy commented on themes/damal/components/FormInput.vue
> +    <input v-bind:type="type" v-bind:name="name" required v-model="input" />
“v-bind:” can be shorten to just “:”

2020-09-25 09:44 UTC, davidmeirlevy commented on themes/damal/components/FormInput.vue
> +<style>
Use scoped css

2020-09-25 09:44 UTC, davidmeirlevy commented on themes/damal/components/FormInput.vue
> +input[type="submit"] {
A submit is usually a button, not an input.

2020-09-25 10:09 UTC, dani98000 commented on themes/damal/components/Form.vue
> +<style scoped>
I can change this by adding a few scoped style. I'm not familiar with Vue best practices yet so i though maybe this was the way to handle this

2020-09-25 13:05 UTC, davidmeirlevy requested changes
Also, we need signin and signup pages for all themes, also for classic and default themes.

2020-09-25 13:05 UTC, davidmeirlevy commented on themes/damal/components/SignIn.vue
> +<template>
A major page component of a theme must be on the theme top level folder, and not inside the “components” folder.

2020-09-25 13:05 UTC, davidmeirlevy commented on themes/damal/components/SignUp.vue
> +<template>
A major page component of a theme must be on the theme top level folder, and not inside the “components” folder.

2020-09-25 14:24 UTC, dani98000 commented
> Also, we need signin and signup pages for all themes, also for classic and default themes.

I'll handle this in the next PR

2020-09-25 15:13 UTC, davidmeirlevy reviewed
From the code it looks great.
I’ll run it later today to look for running errors.

2020-09-27 09:46 UTC, davidmeirlevy commented
I checked it, it looks great. really.
Just add a `signin` and `signup` pages to the `classic` and `default` themes as well, because it can't be merged without it (the build will fail for those themes), and it's great!

Thanks.

2020-09-28 13:20 UTC, davidmeirlevy commented on .vscode/settings.json
> +{
add this folder to gitgnore and make sure it will not be committed.

2020-09-28 13:28 UTC, davidmeirlevy commented
make sure to add `.vscode` directory to `gitignore` and `dockerignore` and make sure this folder doesn't exist in git.

2020-09-29 06:24 UTC, davidmeirlevy approved these changes

2020-09-29 06:24 UTC, merged