moved iseInputValidators.js validates.js (iss #39)
greenpress/blog-front pull request #40
Opened 2020-10-25 22:25 UTC by mihailot01

2020-10-26 08:17 UTC, davidmeirlevy requested changes
Those compositions are used in all 3 themes.
The imports should be changed there too.

2020-10-26 08:17 UTC, davidmeirlevy commented on themes/default/components/SignupForm.vue
> +  import { isEmail } from '../../../compositions/validators'
Please import them with the shortcut to "~compositions/.."

2020-10-26 08:17 UTC, davidmeirlevy commented on themes/default/components/SigninForm.vue
> +	import { isEmail } from '../../../compositions/validators'
Please import them with the shortcut to "~compositions/.."

2020-10-26 08:17 UTC, davidmeirlevy commented on themes/default/components/FormInput.vue
> +} from "../../../compositions/validators";
Please import them with the shortcut to "~compositions/.."

2020-10-26 09:51 UTC, mihailot01 commented on themes/default/components/FormInput.vue
> +} from "../../../compositions/validators";
Can you explain or give me some reference what does it mean: with the shortcut to "~compositions/.." ?

2020-10-26 11:13 UTC, davidmeirlevy commented on themes/default/components/FormInput.vue
> +} from "../../../compositions/validators";
instead of `from "../../../compositions/validators";` you can try `from "~compositions/validators";`
In Nuxt, the tilda (~) is a reference to the main library of the application, and you can also use `~[folder-name]` to get directly into a folder inside the main location.

2020-10-26 21:48 UTC, mihailot01 commented
I tried `from "~compositions/validators";` but it didn't work on my machine. I changed import in all 3 themes.

2020-10-27 07:03 UTC, davidmeirlevy commented
Weird, that's from the Nuxt documentation.
Maybe use "~/compositions/..".

2020-10-27 17:21 UTC, mihailot01 commented
> 
> 
> Weird, that's from the Nuxt documentation.
> Maybe use "~/compositions/..".

It worked 👍🏻

2020-10-28 11:50 UTC, davidmeirlevy approved these changes

2020-10-28 11:51 UTC, merged

2020-10-28 11:51 UTC, davidmeirlevy commented
Great! Thanks!